[theme]
primaryColor = "#1565C0"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#424242"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[logger]
level = "info"
messageFormat = "%(asctime)s - %(message)s"

[client]
showErrorDetails = true
toolbarMode = "auto"

[runner]
fastReruns = true
magicEnabled = true 